node {
    stage('Checkout') {
        git branch: 'react-app', url: 'https://github.com/ahqsa24/a428-cicd-labs.git'
    }

    stage('Install Dependencies') {
        sh 'npm install'
    }

    stage('Build') {
        sh 'npm run build'
    }

    stage('Test') {
        sh 'npm test'
    }

    stage('Deploy') {
        echo 'Deploying application...'
    }
}